<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Amazon.SQS.ExtendedClient" Version="1.7.0" />
    <PackageVersion Include="Aws4RequestSigner" Version="1.0.3" />
    <PackageVersion Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.102.1" />
    <PackageVersion Include="GoogleAuthenticator" Version="3.2.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="SEOChecker.Core" Version="17.0.4" />
    <PackageVersion Include="SEOChecker.Library" Version="17.0.4" />
    <PackageVersion Include="System.Text.Encodings.Web" Version="10.0.12" />
    <PackageVersion Include="Umbraco.Cms.Core" Version="17.7.0" />
    <PackageVersion Include="Umbraco.Cms.Infrastructure" Version="17.7.0" />
    <PackageVersion Include="Umbraco.Cms.Web.Common" Version="17.7.0" />
    <PackageVersion Include="Umbraco.Community.CSPManager" Version="17.0.5" />
  </ItemGroup>
</Project>